# The URL the site will be built for
base_url = "/"
default_language = "de"

title = "Kreativität trifft Technik e.V."
description = "Website des Kreativität trifft Technik e.V."
author = "Markus Framer"

# Compilation settings
compile_sass = true
minify_html = true
build_search_index = true
generate_feed = true
feed_filename = "rss.xml"

taxonomies = [
    {name = "Serie", feed = true, paginate_by = 10 },
    {name = "Typ", feed = true, paginate_by = 10 },
    {name = "Gruppe", feed = true, paginate_by = 10 }
]

[link_checker]
skip_prefixes = []
skip_anchor_prefixes = []
internal_level = "error"
external_level = "error"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"
paths_keep_dates = false

[markdown]
highlight_code = true
render_emoji = false
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = true
lazy_async_image = true

[translations]
language = "Sprache"
not_found_content = "Dies sind nicht die Inhalte die ihr sucht!"
not_found = "Inhalt nicht gefunden"
locale_name = "de_DE"
publish_time = "veröffentlicht am %date% um %time% Uhr von %author%"
all = "Alle"
images = "Bilder"

[extra]
ifs_base_path = "https://www.mainframe.io/media/ifs-images"
resource_base = "https://ktt-ol.github.io"
bs_color_map = [
    "primary",
    "secondary",
    "success",
    "danger",
    "warning",
    "info",
    "light"
]

[languages.en]
title = "Kreativität trifft Technik e.V."
description = "Website of Kreativität trifft Technik e.V."

# Compilation settings
compile_sass = true
minify_html = true
build_search_index = true
generate_feed = true
feed_filename = "rss.xml"

taxonomies = [
    {name = "Series", feed = true, paginate_by = 10 },
    {name = "Type", feed = true, paginate_by = 10 },
    {name = "Group", feed = true, paginate_by = 10 }
]

[languages.en.translations]
language = "Language"
not_found_content = "This is not the content you are looking for!"
not_found = "Content not found"
locale_name = "en_US"
publish_time = "published on %date% at %time% by %author%"
all = "All"
images = "Images"

status_finished = "Finished"
status_in_progress = "In Progress"
