# The URL the site will be built for
base_url = "https://ktt-ol.de"

title = "Kreativität trifft Technik e.V."
description = ""
author = "KTT Webmaster"
default_language = "de"

# Compilation settings
minify_html = true
build_search_index = true
generate_feed = true

[link_checker]
skip_prefixes = []
skip_anchor_prefixes = []
internal_level = "error"
external_level = "error"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"
paths_keep_dates = false

[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_javascript"

[translations]

[languages.en]
title = "Kreativität trifft Technik e.V."
description = ""
author = "KTT Webmaster"
default_language = "de"

# Compilation settings
minify_html = true
build_search_index = true
generate_feed = true

[languages.en.search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_javascript"

[languages.en.translations]

[markdown]
highlight_code = true
render_emoji = false
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = true
lazy_async_image = true

[extra]